# Generated by Django 4.1.1 on 2023-03-04 08:42

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjobdata',
            name='slud_ref',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='job_title', unique=True),
        ),
        migrations.AlterField(
            model_name='postjobdata',
            name='job_image',
            field=models.ImageField(upload_to='user_uploaded_imgs/'),
        ),
    ]
